# Generated by Django 3.2.6 on 2022-05-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20220520_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='load_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
