# Generated by Django 3.2.6 on 2022-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20220520_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор документа'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='description',
            field=models.TextField(null=True, verbose_name='Краткое описание документа'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='doc_from',
            field=models.CharField(max_length=255, null=True, verbose_name='Отдел откуда документ'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='theme',
            field=models.CharField(max_length=255, null=True, verbose_name='Тема документа'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='type',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='number',
            field=models.IntegerField(verbose_name='Номер договора'),
        ),
    ]
