# Generated by Django 3.2.6 on 2022-05-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20220526_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Приватность (поставьте галочку, если больше никто не должен видеть этот докумени)'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название договора'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер договора'),
        ),
    ]
