# Generated by Django 3.2.6 on 2022-05-30 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_auto_20220530_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='action',
            field=models.CharField(choices=[('read', 'Ознакомление'), ('submited', 'Подпись')], default='read', max_length=255, verbose_name='Вид документа'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='submited',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 21, 35, 41, 112182), null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='status',
            field=models.CharField(choices=[('added', 'Создан'), ('waiting', 'Ожидает'), ('read', 'Ознакомлен'), ('terminated', 'Расторгнут'), ('submited', 'Подписан'), ('executed', 'Исполнен')], default='added', max_length=255, verbose_name='Статус документа'),
        ),
        migrations.RemoveField(
            model_name='documentmodel',
            name='user_to',
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому'),
        ),
    ]
