# Generated by Django 3.2.6 on 2022-05-30 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20220530_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='action',
            field=models.CharField(choices=[('read', 'Ознакомление'), ('submited', 'Подпись')], default='read', max_length=255, verbose_name='Отправить на..'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 22, 54, 55, 385652), null=True, verbose_name='Дата окончания'),
        ),
    ]
