# Generated by Django 3.2.6 on 2022-06-03 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20220530_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 9, 28, 58, 42160), null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='type',
            field=models.CharField(choices=[('statement', 'Заявление'), ('reference', 'Справка'), ('order', 'Поручение'), ('act', 'Акт'), ('contract', 'Договор'), ('decree', 'Приказ')], default='contract', max_length=255, null=True, verbose_name='Тип документа'),
        ),
    ]
